### ISSUE TITLE
preference changes not persisting ref #23

### ISSUE THREAD

**Issue by thehogfather** [thehogfather/brackets-latex#25]
Changes to preferences (e.g., output directory) not being persisted correctly. (ref taken from #23)

**Comment by thehogfather** [comment]
@machocam could you check if there are any error messages related to the extension in the console? Go to `Debug > Show Developer Tools` and copy and paste any error messages here. I am still unable to reproduce the issue.

**Comment by machocam** [comment]
Here is the output, sorry about the formatting.

per.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _attachExtensionManagerListener (/main.js:118:9)
    at _appReadyHandler (/main.js:289:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on
Brackets modules and model objects. Call on()/off() directly on the object
without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _setupAbandonmentEvents (/main.js:234:9)
    at _appReadyHandler (/main.js:291:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on
Brackets modules and model objects. Call on()/off() directly on the object
without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at _appReadyHandler (/main.js:294:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.eval (/main.js:304:17)
    at j
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith]
(file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
/utils/DeprecationWarning.js:90 Use WorkspaceManager.createBottomPanel()
instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at showConsolePanel
(file:///Users/Rodrigo/Library/Application%20Support/Brackets/extensions/user/brackets-latex/ConsolePanel.js:46:41)
    at Object.exports.show
(file:///Users/Rodrigo/Library/Application%20Support/Brackets/extensions/user/brackets-latex/ConsolePanel.js:82:9)
    at
file:///Users/Rodrigo/Library/Application%20Support/Brackets/extensions/user/brackets-latex/main.js:174:38
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1081:29)

**Comment by thehogfather** [comment]
@machocam apologies for the  silence. Can you confirm if any of the other preferences are persisted? And is there a .brackets.json file in the project root when after clicking save on the Latex Settings Dialog?

**Comment by machocam** [comment]
All other settings revert to defaults too (tried with the compiler and bin
directory). There doesn't seem to be a json file in the root of my project.
Yes, I did look for hidden files.

By root you mean the location of the orginal tex file right?

**Comment by thehogfather** [comment]
by root I mean the brackets project folder - this may or may not be the location of the original tex file. The tex file might reside in a subfolder in the project folder.

I suspect something funny is happening when you the file is about to be persisted. If you can edit the .brackets.json file and add  the following entry:

          "brackets-latex.outputDirectory": "."

The save the file and open the settings dialog. Let me know if this updates the value on the dialog.

**Comment by adakite** [comment]
Hi, I have the very same issue. 
Editing .brackets.json does not make any change. That is really annoying. The default should be "." as most people want the compiled files in the same directory as the source'. 

Any chance for fixing that issue?

thanks though for this neat plugin!

**Comment by adakite** [comment]
I fixed by editing  CompiledLatex.js
and replace
var dir = path.resolve(options.projectRoot, options.outputDirectory);
by
var dir = folderName; //path.resolve(options.projectRoot, options.outputDirectory);

**Comment by adilsoncasula** [comment]
This is a really old problem. But it still happens here. 
Any of above "changes" had worked.
